bldr:
    name: gushphp/gush
    description: Gush Project
    profiles:
        travis:
            description: Travis Profile
            jobs:
                - prepare
                - test
        local:
            description: Local Development Profile
            jobs:
                - testLocal
                - watch
        rebase:
            description: Gush rebase flow
            jobs:
                - gushRebase
        merge:
            description: Gush merge flow
            jobs:
                - gushMerge
        minor:
            description: minor run
            jobs:
                - minor
        major:
            description: major run
            jobs:
                - major
        patch:
            description: patch run
            jobs:
                - patch
    jobs:
        prepare:
            tasks:
                -
                    continueOnError: true
                    type: filesystem:remove
                    files: [build/coverage, build/logs]
                -
                    type: filesystem:mkdir
                    continueOnError: false
                    files: [build/coverage, build/logs]
                -
                    type: filesystem:touch
                    continueOnError: true
                    files: [build/coverage/index.html]
                -
                    type: exec
                    continueOnError: true
                    executable: composer
                    arguments: [install]
        test:
            description: Runs the PHPUnit Tests
            tasks:
                -
                    type: exec
                    continueOnError: false
                    executable: phpunit
                    arguments:
                        - --verbose
                        - --exclude-group=""
                        - --coverage-html=build/coverage
                        - --coverage-text=php://stdout
        testLocal:
            description: Runs the PHPUnit Tests
            tasks:
                -
                    type: exec
                    continueOnError: true
                    executable: phpunit
                    arguments:
                        #- --group=now
        watch:
            description: Watch Task for Local Development
            tasks:
                -
                    type: watch
                    src:
                        - { path: [src, tests], files: "*.php", recursive: true }
                    task: testLocal
        gushRebase:
            description: Gush rebase flow
            tasks:
                -
                    type: gush:branch:rebase
                    base_branch: master
        gushMerge:
            description: Gush merge flow
            tasks:
                -
                    type: gush:pull-request:merge
                    base_branch: master
                    symlinked: true
        minor:
            description: Gush block tag minor release
            tasks:
                -
                    type: gush:branch:tag
                    base_branch: master
                    release: minor
        major:
            description: Gush block tag major release
            tasks:
                -
                    type: gush:branch:tag
                    base_branch: master
                    release: major
        patch:
            description: Gush block tag patch release
            tasks:
                -
                    type: gush:branch:tag
                    base_branch: master
                    release: patch
