bldr:
    name: gushphp/gush
    description: Gush Project
    profiles:
        travis:
            description: Travis Profile
            tasks:
                - prepare
                - lint
                - test
                - secure
        local:
            description: Local Development Profile
            tasks:
                - testLocal
                - watch
        rebase:
            description: Gush rebase flow
            tasks:
                - gushRebase
        merge:
            description: Gush merge flow
            tasks:
                - gushMerge
        secure:
            description: run security script
            tasks:
                - secure
    tasks:
        prepare:
            calls:
                -
                    failOnError: false
                    type: filesystem:remove
                    files: [build/coverage, build/logs]
                -
                    type: filesystem:mkdir
                    failOnError: true
                    files: [build/coverage, build/logs]
                -
                    type: filesystem:touch
                    failOnError: false
                    files: [build/coverage/index.html]
                -
                    type: exec
                    failOnError: true
                    executable: composer
                    arguments: [-q, install, --prefer-dist]
                -
                    type: notify
                    message: Prepare Task Finished
        secure:
            calls:
                -
                    type: exec
                    failOnError: false
                    executable: rm
                    arguments:
                        - ./security-checker.phar
                -
                    type: exec
                    failOnError: false
                    executable: wget
                    arguments:
                        - http://get.sensiolabs.org/security-checker.phar
                -
                    type: exec
                    failOnError: false
                    executable: chmod
                    arguments:
                        - +x
                        - ./security-checker.phar
                -
                    type: exec
                    failOnError: true
                    executable: php
                    arguments:
                        - ./security-checker.phar
                        - security:check
                        - ./composer.lock
        lint:
            description: Lints the files of the project
            calls:
                -
                    type: apply
                    failOnError: true
                    src:
                        - { path: [src, tests], files: *.php, recursive: true }
                    output: /dev/null
                    executable: php
                    arguments: [-l]
        test:
            description: Runs the PHPUnit Tests
            calls:
                -
                    type: exec
                    failOnError: true
                    executable: php
                    arguments:
                        - bin/phpunit
                        - --coverage-html=build/coverage
                        - --coverage-text=php://stdout
        testLocal:
            description: Runs the PHPUnit Tests
            calls:
                -
                    type: exec
                    executable: php
                    arguments:
                        - bin/phpunit
                        - --group=now
        watch:
            description: Watch Task for Local Development
            calls:
                -
                    type: watch
                    src:
                        - { path: [src, tests], files: *.php, recursive: true }
                    task: testLocal
        gushRebase:
            description: Gush rebase flow
            calls:
                -
                    type: gush:branch:rebase
                    base_branch: master
        gushMerge:
            description: Gush merge flow
            calls:
                -
                    type: gush:pull-request:merge
                    base_branch: master
                    symlinked: true
