# Gush configuration file, any comments will be lost.
meta-header: "This file is part of Gush package.\n\n(c) Luis Cordova <cordoval@gmail.com>\n\nThis source file is subject to the MIT license that is bundled\nwith this source code in the file LICENSE."
pr_type:
    - feature
    - bugfix
    - refactor
    - tests
    - remove
    - style
    - documentation
    - security
table-pr:
    fixed_tickets: ['Fixed tickets', '']
    license: [License, MIT]
base: master
repo_adapter: github
issue_tracker: github
repo_org: gushphp
repo_name: gush
issue_project_org: gushphp
issue_project_name: gush
pats:
    good_job: 'Good job @{{ author }}.'
    you_were_fast: 'You were fast on this one, thanks @{{ author }}.'
    good_catch: 'Good catch @{{ author }}, thanks for the patch.'
    thank_you: 'Thank you @{{ author }}.'
    good_catch_thanks: 'Good catch, thanks @{{ author }}.'
    thanks_for_pr: 'Thanks @{{ author }} for the pull request!'
    well_done: 'Well done @{{ author }}.'
    beers: ':beers: @{{ author }}.'
adapters:
    github: { base_url: 'https://api.github.com/', repo_domain_url: 'https://github.com', authentication: { username: coder20078, token: something }}
