language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer install

matrix:
    allow_failures:
        - php: hhvm
env:
  - GUSH_HOME=/tmp/gush GUSH_CACHE_DIR=/tmp/gush/cache

script:
  - phpunit
