#
# This file is part of Gush.
#
# (c) Luis Cordova <cordoval@gmail.com>
#
# This source file is subject to the MIT license that is bundled
# with this source code in the file LICENSE.
#

language: php

php:
    - 5.5
    - 5.6
    - 7.0

matrix:
    allow_failures:
        - php: 7.0
    fast_finish: true

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

env:
    - GUSH_USE_FS=true
    - GUSH_USE_FS=false

before_install:
    - composer self-update
    #- curl -sS http://bldr.io/installer | php

script:
    - php ./bldr.phar run travis
    - php ./bldr.phar run secure
