##
# This file is part of Gush.
#
# (c) Luis Cordova <cordoval@gmail.com>
#
# This source file is subject to the MIT license that is bundled
# with this source code in the file LICENSE.
#

language: php

php: [5.5, hhvm]

matrix:
    allow_failures:
        - php: hhvm

env:
  # RUNSCOPE_BUCKET= VERSIONEYE_TOKEN= GUSH_HOME=/tmp/gush GUSH_CACHE_DIR=/tmp/gush/cache
  - secure: "L2Vi72Dr0mH7tBcPHXHd4c1XICKgD5S1niSF1UN+rW1bojjnerDPU6+wOaCl9FyNKXDsUkVjtG4JowX4XJ3gn50DfYZC/ujBf93zVSS86NCSbtaVJxqKeyi1y9KwAjMQX5unlGyXSrpZnL6XqHMfKny0VH5VISc6BhwYFKG0+94="

before_script:
  - composer self-update
  - composer install

script:
  - phpunit

notifications:
  irc: "irc.freenode.org#gushphp"
