##
# This file is part of Gush.
#
# (c) Luis Cordova <cordoval@gmail.com>
#
# This source file is subject to the MIT license that is bundled
# with this source code in the file LICENSE.
#

language: php

php: [5.4, 5.5, 5.6, hhvm]

matrix:
    allow_failures:
        - php: hhvm

env:
  # VERSIONEYE_TOKEN= GUSH_HOME=/tmp/gush GUSH_CACHE_DIR=/tmp/gush/cache
  - secure: "hwEam4w4t7TQg3R38sR8fpLVkt/j6d73RyVB3viNWNYO26YAr2YzRnekL7ysd1mvgy/AMK9A4iDGJ7eyPJ4+R3aKmhBGVUz78cdRdPfm+6ZJp/XqydRklVQrgKEJKlaUVDj6oDws3mGILTxfdZsfHD11XI3+Piut0mF4b5pXRZU="

before_script:
  - composer self-update
  - curl -sS http://bldr.io/installer | php

script:
  - ./bldr.phar build -p travis

notifications:
  irc: "irc.freenode.org#gushphp"
