#
# This file is part of Gush.
#
# (c) Luis Cordova <cordoval@gmail.com>
#
# This source file is subject to the MIT license that is bundled
# with this source code in the file LICENSE.
#

language: php

php: [5.4, 5.5, hhvm]

matrix:
    allow_failures:
        - php: hhvm

env:
  - GUSH_HOME=/tmp/gush GUSH_CACHE_DIR=/tmp/gush/cache

before_script:
  - composer install -n

script:
  - phpunit

notifications:
  irc: "irc.freenode.org#gushphp"
