#
# This file is part of Gush.
#
# (c) Luis Cordova <cordoval@gmail.com>
#
# This source file is subject to the MIT license that is bundled
# with this source code in the file LICENSE.
#

language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: 7.0
        - php: hhvm-nightly
    fast_finish: true

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

env:
    - GUSH_HOME=/tmp/gush GUSH_CACHE_DIR=/tmp/gush/cache

before_install:
    # this is needed because something is broken in hhvm
    #- composer self-update
    #- curl -sS http://bldr.io/installer | php

script:
    - php ./bldr.phar run travis
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then php ./bldr.phar run secure; fi;'

notifications:
    irc: "irc.freenode.org#gushphp"
