##
# This file is part of Gush.
#
# (c) Luis Cordova <cordoval@gmail.com>
#
# This source file is subject to the MIT license that is bundled
# with this source code in the file LICENSE.
#

language: php

php: [5.5, hhvm]

matrix:
    allow_failures:
        - php: hhvm

env:
  # RUNSCOPE_BUCKET= VERSIONEYE_TOKEN= GUSH_HOME=/tmp/gush GUSH_CACHE_DIR=/tmp/gush/cache
  - secure: "Ii55ivFDOzWxhc856TYFxcd5y171fl0/KpnxpiAZx/2PhC8+nJ0Az0J5bkvhDp341fzMarBM01tqeBlbQxEUshOEqijQeu4avSdmcf2YvDEpoXYhi50K22XzzlBbFXZuD076bt+uWdXT4UxyvFUbjHp6eDEfM7EKi/Xszg4zVdU="

before_script:
  - composer require gushphp/gush-github-adapter=dev-master
  - composer install -n

script:
  - phpunit

notifications:
  irc: "irc.freenode.org#gushphp"
